name: HeyTelecom Add-on
version: "0.1.2"
slug: heytelecom-addon
description: Backend service for the HeyTelecom integration

image: "ghcr.io/maurodruwel/heytelecom"

arch:
  - amd64
  - aarch64

startup: application

options:
  email: ""
  password: ""

schema:
  email: email
  password: password
